import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body>
        <div className="border-b-2 flex justify-between px-8 py-4 items-center">
          <h3 className="text-red-500 font-bold text-xl">My App</h3>
          <Link href={"/signin"} className="border-2 border-black px-4 py-2 rounded-lg">Sign In</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
