import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <div className="border-b-2 flex justify-between px-8 py-4 items-center">
          <h3 className="text-red-500 font-bold text-xl">My App</h3>
          <button className="border-2 border-black px-4 py-2 rounded-lg">Sign In</button>
        </div>
        {children}
      </body>
    </html>
  );
}
